baseurl = "http://georgelangham.me/"
disqusShortname = "GeorgeWL"
googleAnalytics = ""
languageCode = "en-us"
publishDir = "docs"
theme = "hugo-creative-portfolio-theme"
title = "George W Langham"
[params]
copyright = "&copy;2017 George W Langham"
date_format = "January 2, 2006"
description = "George W Langham's Portfolio"
email = "hello@georgelangham.me"
googlemapsapikey = ""
sidebarabout = ["Web and Mobile Developer."]
style = "sea"
[params.carousel]
enable = false
[params.clients]
enable = false
subtitle = ""
title = "Our Clients"
[params.features]
enable = false
[params.recent_posts]
enable = true
subtitle = ""
title = ""
[params.see_more]
enable = false
icon = "fa fa-file-code-o"
link_text = "Check other homepages"
link_url = "#"
subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
title = "Do you want to see more?"
[params.social]
email = "hello@georgelangham.me"
facebook = "https://www.facebook.com/georgelangham.me/"
github = "https://github.com/GeorgeWL"
linkedin = "https://uk.linkedin.com/in/georgewlangham"
twitter = "https://twitter.com/langhamgeorge"
[params.testimonials]
enable = false
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."
title = "Testimonials"
[params.widgets]
categories = false
search = true
tags = false
[[params.navlinks]]
name = "Home"
url = ""
[[params.navlinks]]
name = "About"
url = "about/"
[[params.navlinks]]
name = "Blog"
url = "blog/"
[[params.navlinks]]
name = "Contact Me"
url = "contact/"
